# Generated by Django 3.2.5 on 2021-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('Idno_or_passport', models.IntegerField(verbose_name=8)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phonenumber', models.CharField(max_length=13)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField(verbose_name=5)),
                ('course', models.CharField(max_length=30)),
                ('date_of_birt', models.DateTimeField(auto_now=True)),
                ('marital_status', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('digital_signature', models.CharField(max_length=500)),
            ],
        ),
    ]
