# Generated by Django 3.2.5 on 2021-07-14 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificateissuer', '0002_remove_student_digital_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='digital_signature',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
