# Generated by Django 3.2.5 on 2021-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificateissuer', '0003_student_digital_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Idno_or_passport',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
